on:
  push:
    branches:
    - develop

jobs:
  deploy_dev:
    name: Pull latest develop and redeploy dev instance
    runs-on: ubuntu-latest

    steps:
    - name: SSH dev pull and build
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: dev.openaccessbutton.org
        user: ${{secrets.USER_TEST_V1}}
        private_key: ${{secrets.GA_ED25519}}
        host_fingerprint: ${{secrets.FINGERPRINT_TEST_V1}}
        command: cd ~/dev/oaworks/embed && git pull && cd ~/dev/openresearchbutton/website && git pull && node build.js && sudo nginx -s reload
